# Generated by Django 5.0.7 on 2025-01-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0004_remove_trainingsession_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
