# Generated by Django 5.0.7 on 2025-01-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0005_trainerapplication_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerapplication',
            name='age',
        ),
    ]
