# Generated by Django 5.0.7 on 2025-01-20 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0009_remove_traineeapplication_artisan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalreport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='linked_activity',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='stcform',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='requisitionapprovalcomment',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='requisitionapprovalcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stcform',
            name='activity_report',
        ),
        migrations.CreateModel(
            name='UnifiedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STC', 'STC'), ('REQ', 'Requisition'), ('ACT', 'Activity'), ('NORM', 'Normal Report')], help_text='Type of report (STC, Requisition, Activity, Normal).', max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('report_file', models.FileField(blank=True, help_text='Attach any relevant file (PDF, doc, etc.)', null=True, upload_to='reports_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_approver', models.ForeignKey(blank=True, help_text='The user responsible for approving/rejecting this report.', limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to_approve', to=settings.AUTH_USER_MODEL)),
                ('attached_report', models.ForeignKey(blank=True, help_text='Optionally attach a previously approved report.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='urdt_app.unifiedreport')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, help_text='Select users who can view this report once approved.', limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), related_name='viewable_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='urdt_app.unifiedreport')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveForm',
        ),
        migrations.DeleteModel(
            name='NormalReport',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.DeleteModel(
            name='RequisitionApprovalComment',
        ),
        migrations.DeleteModel(
            name='STCForm',
        ),
    ]
