# Generated by Django 5.0.7 on 2025-01-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0010_remove_normalreport_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='attached_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urdt_app.unifiedreport'),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports_files/'),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='report_type',
            field=models.CharField(choices=[('STC', 'STC'), ('REQ', 'Requisition'), ('ACT', 'Activity'), ('NORM', 'Normal Report')], max_length=4),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='viewers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), related_name='viewable_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
