# Generated by Django 5.0.7 on 2025-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0012_unifiedreport_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeapplication',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerapplication',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traineeapplication',
            name='nature_of_disability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
