# Generated by Django 5.0.7 on 2025-01-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0016_safeguardingchatsession_safeguardingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
