# Generated by Django 5.0.7 on 2025-01-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0018_remove_safeguardingmessage_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeguardingmessage',
            name='case',
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='seen_by_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safeguardingmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safeguardingmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='SafeguardingCase',
        ),
    ]
