# Generated by Django 5.0.7 on 2025-01-25 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0019_remove_safeguardingmessage_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeguardingmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='safeguardingmessage',
            name='seen_by_officer',
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='trainee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urdt_app.traineeapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safeguardingmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
