# Generated by Django 5.0.7 on 2025-01-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0020_remove_safeguardingmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainerapplication', to=settings.AUTH_USER_MODEL),
        ),
    ]
