# Generated by Django 5.0.7 on 2025-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0025_remove_safeguardingmessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeapplication',
            name='dit_status',
            field=models.CharField(blank=True, choices=[('NOT_REGISTERED', 'Not Registered for DIT'), ('REGISTERED', 'Registered for DIT')], help_text='Tracks whether the trainee is registered for DIT assessment.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='traineeapplication',
            name='final_assessment_status',
            field=models.CharField(choices=[('NONE', 'No Assessment Yet'), ('SUCCESSFUL', 'Successfully Assessed'), ('UNSUCCESSFUL', 'Unsuccessful'), ('ABSENT', 'Absent')], default='NONE', help_text="Registrar's final assessment status.", max_length=15),
        ),
        migrations.AddField(
            model_name='traineeapplication',
            name='study_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED_STUDYING', 'Started Studying'), ('COMPLETED', 'Completed'), ('DROPPED_OUT', 'Dropped Out')], default='NOT_STARTED', help_text="Tracks the trainee's study progress from not started -> started -> completed or dropped out.", max_length=20),
        ),
    ]
