# Generated by Django 5.0.7 on 2025-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0028_traineeapplication_dit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='epicenter_manager',
        ),
        migrations.DeleteModel(
            name='RelevantData',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ActivityPlan',
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
    ]
