# Generated by Django 5.0.7 on 2025-02-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0030_unifiedreport_assigned_checker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stcbudgetline',
            name='stc_report',
        ),
        migrations.RemoveField(
            model_name='stcreport',
            name='unified_report',
        ),
        migrations.RemoveField(
            model_name='unifiedreport',
            name='assigned_checker',
        ),
        migrations.RemoveField(
            model_name='unifiedreport',
            name='checked_at',
        ),
        migrations.RemoveField(
            model_name='unifiedreport',
            name='checked_by',
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='approved_at',
            field=models.DateField(blank=True, help_text='Date when the report was approved', null=True),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, help_text='The user responsible for approving/rejecting this report.', limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='attached_report',
            field=models.ForeignKey(blank=True, help_text='Optionally attach a previously approved report.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='urdt_app.unifiedreport'),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='Attach any relevant file (PDF, doc, etc.)', null=True, upload_to='reports_files/'),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Select users who can view this report once approved.', limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), related_name='viewable_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='STCActionPlanLine',
        ),
        migrations.DeleteModel(
            name='STCBudgetLine',
        ),
        migrations.DeleteModel(
            name='STCReport',
        ),
    ]
