# Generated by Django 5.0.7 on 2025-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0032_stcreport_stccomment_stcbudgetline_stcactionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcreport',
            name='grand_total',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
