# Generated by Django 5.0.7 on 2025-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0033_stcreport_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcreport',
            name='project_name',
            field=models.CharField(default='damn', max_length=255),
            preserve_default=False,
        ),
    ]
