# Generated by Django 5.0.7 on 2025-02-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0034_stcreport_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='ACTIVITY', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, help_text='Date of the activity', null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('key_activities_conducted', models.TextField(blank=True)),
                ('results_of_activity_findings', models.TextField(blank=True)),
                ('emerging_issues_key_lesson', models.TextField(blank=True)),
                ('challenges_and_mitigation', models.TextField(blank=True)),
                ('key_actions_recommendations', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_approver', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_reports_to_approve', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_prepared_reports', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), related_name='activity_viewable_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='urdt_app.activityreport')),
            ],
        ),
    ]
