# Generated by Django 5.0.7 on 2025-02-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0035_activityreport_activitycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='urdt_app.activityreport')),
            ],
        ),
    ]
