# Generated by Django 5.0.7 on 2025-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0037_customuser_data_entrant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeguardingmessage',
            name='staff_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='trainee_read',
            field=models.BooleanField(default=False),
        ),
    ]
