# Generated by Django 5.0.7 on 2025-02-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0038_safeguardingmessage_staff_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='LEAVE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED', 'Checked'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('type_of_leave', models.CharField(blank=True, help_text='Comma-separated leave types chosen', max_length=255)),
                ('other_leave_text', models.CharField(blank=True, help_text="If 'Other' is chosen", max_length=255)),
                ('previous_allocation', models.CharField(blank=True, max_length=100)),
                ('taken', models.CharField(blank=True, max_length=100)),
                ('remaining', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_days', models.CharField(blank=True, max_length=50)),
                ('resuming_work_day', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_approver', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reports_to_approve', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_prepared_reports', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__in', ['TRAINER', 'TRAINEE']), _negated=True), related_name='leave_viewable_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='urdt_app.leavereport')),
            ],
        ),
    ]
