# Generated by Django 5.0.7 on 2025-02-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0041_traineeapplication_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeapplication',
            name='student_number',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True, unique=True),
        ),
    ]
