# Generated by Django 5.0.7 on 2025-02-07 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0042_alter_traineeapplication_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeguardingmessage',
            name='staff_read',
        ),
        migrations.RemoveField(
            model_name='safeguardingmessage',
            name='trainee_read',
        ),
        migrations.AddField(
            model_name='safeguardingmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
