# Generated by Django 5.0.7 on 2025-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urdt_app', '0043_remove_safeguardingmessage_staff_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the trainer is currently active.'),
        ),
    ]
